main:
  - name: Home
    url: ""
    weight: 1
  - name: About
    url: "#about"
    weight: 2
  - name: Intake/Referral Forms
    url: ""
    weight: 4
  - name: Services/Pricing
    url: "#service"
    weight: 3
  - name: Faqs
    url: "#resume"
    weight: 5
  - name: Mental Health Resources
    url: "#product"
    weight: 6
  # - name: Testimonials
  #   url: "#testimonial"
  #   weight: 6
  # - name: Blog
  #   url: "#blog"
  #   weight: 7
sitemap:
  - name: Home
    url: ""
    weight: 1
  - name: Contact Us
    url: "contact"
    weight: 2
  - name: Products
    url: "product"
    weight: 3
  - name: Blog
    url: "blog"
    weight: 4
