baseURL = ""
languageCode = "en-us"
title = "IT Solutions"
theme = "hugo-hero-theme"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.92.0"
    
[params]
  google_analytics_id=""
  background = "images/jason.webp"
  fabFormURL = "https://getform.io/f/08844677-7d69-419c-bedb-9d08f14b0ffb"
  [params.logo]
    mobile = "images/logo-mobile.png"
    mobile_height = "36px"
    mobile_width = "36px"
    desktop = "images/logo.png"
    desktop_height = "29px"
    desktop_width = "217px"
    alt = "Hugo Hero"

  [params.homepage_meta_tags]
    meta_description = "Boost your business with cutting-edge technology and innovative solutions."
    meta_og_title = "Hugo Hero Theme"
    meta_og_type = "website"
    meta_og_url = "https://hugo-hero.netlify.app"
    meta_og_image = "https://raw.githubusercontent.com/JugglerX/hugo-hero-theme/master/images/tn.png"
    meta_og_description = "Boost your business with cutting-edge technology and innovative solutions."
    meta_twitter_card = "summary"
    meta_twitter_site = "@zerostaticio"
    meta_twitter_creator = "@zerostaticio"

[[menu.main]]
	name = "Home"
	url = "/"
    weight = 1

[[menu.main]]
    name = "Solutions"
    url = "/solution/"
    weight = 2


[[menu.main]]
    name = "Services"
    url = "/Services/"
    weight = 3

[[menu.main]]
    name = "Contact Us"
    url = "/contact/"
    weight = 4
[permalinks]
  post = "/:year/:month/:day/:slug/"
  pages = "/:filename/"
