[build]
  command = "npm run build"
  publish = "public"

[context.production]
  command = "npm run build"
  publish = "public"

[context.deploy-preview]
  command = "npm run build"
  publish = "public"

[context.branch-deploy]
  command = "npm run build"
  publish = "public"

[build.environment]
  NODE_VERSION = "18"

[plugins]
  [[plugins]]
    package = "@netlify/plugin-cache-nextjs"
  
  [[plugins]]
    package = "netlify-plugin-submit-sitemap"
