[build]
  publish = "public"
  functions = "functions"

[build.environment]
  NODE_VERSION = "18.12.0"
  NPM_VERSION = "8.19.2"
  

[context.production]
  command = "npm install && npm run build"


[context.next.environment]
  HUGO_ENV = "next"

[[plugins]]
  package = "netlify-plugin-submit-sitemap"

	[plugins.inputs]
    baseUrl = "https://hyas.netlify.app/"
    sitemapPath = "/sitemap.xml"
    ignorePeriod = 0
    providers = [
      "google",
      "yandex"
    ]

[dev]
  framework = "#custom"
  command = "npm run start"
  targetPort = 1313
  port = 8888
  publish = "public"
  autoLaunch = false
